var terms = [
	"HDR: Health Data Repository",
	"HEC: Health Executive Council",
	"HHS: Health and Human Services",
	"HIPAA: Health Insurance Portability and Accountability Act",
	"HIT: Health Information Technology",
	"HL7: Health Level 7",
	"HMP: Health Management Platform",
	"HPD: Health Provider Directory ",
	"HPS: Health Provider Systems",
	"HRF: Human Readable Form",
	"HSP: Health Standards Profile",
	"HTTPS: Hypertext Transport Protocol Secure",
	"I2TP: Joint DoD/VA Healthcare Information Interoperability Technical Package",
	"IAA: Inter-Agency Agreement",
	"IAF: Interoperability Alignment Framework ",
	"IAM: Identity and Access Management ",
	"IBPE: Internal Business Partner Extranet ",
	"ICD: International Classification of Diseases ",
	"ICIB:  Interagency Clinical Informatics Board",
	"ICR: Intelligent Character Recognition",
	"ICU: Intensive Care Unit",
	"IEEE: Institute of Electrical and Electronics Engineers",
	"iEHR: Integrated Electronic Health Records",
	"IG: Inspector General",
	"IHI: Institute of Health Improvement ",
	"IIS: Immunization Information System ",
	"IPC: Intake Processing Center",
	"IPT: Integrated Project Team ",
	"ISA: Interagency Service Agreement",
	"ISCM: Information Security Continuous Monitoring ",
	"IT: Information Technology",
	"IU: Individual Unemployability",
	"IV: Intravenous ",
	"JLV: Joint Legacy Viewer",
	"JSON: Java Script Object Notation",
	"LAN: Local Area Network",
	"LIS: Laboratory Information System",
	"LOINC: Logical Observation Identifiers Names and Codes",
	"M-Code: Massachusetts General Hospital Utility Multi-Programming System Code",
	"MD FIRE: Medical Device Free Interoperability Requirements for the Enterprise",
	"MDI: Medical Device Integration",
	"MLLP: Minimum Lower Layer Protocol",
	"MOCHA: Medication Order Check Healthcare Application"
]