var terms = [
	"FHIR: Fast Healthcare Interoperability Resources",
	"NDAA: National Defense Authorization Act",
	"MPLS: Multiprotocol Label Switching",
	"SIM: Strategic Investment Management ",
	"ePrescribing: Electronic prescriptions",
	"CBOC: Community Based Outpatient Clinic",
	"CITE : Community IT Engagement Program ",
	"CCR: Continuity of Care Record",
	"EOS: End of Service",
	"BGS: Benefits Gateway Services",
	"BP: Background Processor ",
	"MVI: Master Veteran Index",
	"DEAP: Disability Examination (assessment?) Program",
	"IEPD: ",
	"TIC: Trusted Internet Connection",
	"CCOW: Clinical Context Object Workgroup",
	"3DES: Triple Data Encryption Algorithm Standard",
	"HRF: Human Readable Form",
	"PRA: Paperwork Reduction Act",
	"ASTM: American Society for Testing and Materials",
	"CTS: Common Terminology Services",
	"eMI: Enterprise Messaging Infrastructure",
	"RPC: Remote Procedure Call",
	"PIES: Personnel Information Exchange Service",
	"VBMS: Veterans Benefits Management System",
	"HSP: Health Standards Profile",
	"RBPS: Rules Based Processing System",
	"XACML: Extensible Access Control Markup Language",
	"FY: Fiscal Year",
	"RIF: Reduction in Force",
	"RxNORM: Normalized naming system for generic and branded drugs",
	"RO: Regional Office",
	"VFE: Virtual Front End",
	"NVSO: National Veteran Service Organization",
	"XDR: External Data Representation",
	"IAM: Identity and Access Management ",
	"DMIX: Defense Medical Information Exchange",
	"EHR: Electronic Health Record",
	"CQM: Clinical Quality Measures",
	"EELS: Enterprise Exception Log Service",
	"DAS: Data Access Service",
	"IAA: Inter-Agency Agreement",
	"PALT: Procurement Acquisition Lead Time",
	"CPE: Clinical Practice Environment ",
	"WRT: With Regards To",
	"VSI: Very Seriously Injured",
	"ISCM: Information Security Continuous Monitoring ",
	"I2TP: Joint DoD/VA Healthcare Information Interoperability Technical Package",
	"COVR: Control of Veteran Records",
	"EOL: End of Life",
	"SHARE: ",
	"FOIA: Freedom of Information Act",
	"PACT: Patient Aligned Care Teams",
	"CVSO: County Veterans Service Office",
	"OM: Office of Management",
	"SHAI: Secure Hash Algorithm",
	"AES: Advanced Encryption Standard",
	"VIE: VistA Interface Engine",
	"OIG: Office of Inspector General",
	"NDCP: National Data Center Program ",
	"EDE: Enterprise Development Environment",
	"CAVC: Court of Appeals for Veterans Claims",
	"OA: Operational Analytics",
	"MOCHA: Medication Order Check Healthcare Application",
	"VADS: Veterans Assistance at Discharge System",
	"VIS: Veterans Information System",
	"API: Application Program Interface",
	"CDW : Corporate Data Warehouse",
	"IPT: Integrated Project Team ",
	"APM: Application Performance Monitoring",
	"DBQ: Disability Benefits Questionnaire",
	"SME: Subject Matter Expert",
	"OP: Outpatient Pharmacy ",
	"FDC: Fully Developed Claim",
	"EA: Enterprise Architecture",
	"DME: Development Modernization & Enhancements",
	"VA: Department of Veterans Affairs",
	"HL7: Health Level 7",
	"GUI: Graphical User Interface",
	"CCDA: Consolidated Clinical Document Architecture",
	"FOUO: For Official Use Only",
	"VACAA: Veterans Access Choice and Accountability Act of 2014",
	"PECS: Pharmacy Enterprise Customization System",
	"CAPRI: Compensation and Pension Record Interchange",
	"XML: Extensible Markup Language ",
	"EMR: Electronic Medical Record",
	"CRADA: Collaborative Research and Development Agreements ",
	"TRM: Technical Reference Model ",
	"OCR: Optical Character Recognition",
	"CMS: Centers for Medicare & Medicaid Services",
	"ISA: Interagency Service Agreement",
	"VE: Veterans Experience",
	"ROI: Release of Information ",
	"DBMS: Database Management System",
	"NWQ: National Work Queue",
	"vBE: Virtual Back End",
	"DR: Disaster Response",
	"HMP: Health Management Platform",
	"O&M: Operations and Maintenance ",
	"PB: Petabyte",
	"HPS: Health Provider Systems",
	"IHI: Institute of Health Improvement ",
	"VM: Virtual Machine ",
	"BCR: Breast Care Registry",
	"NDF-RT: National Drug File Ð Reference Terminology",
	"IEEE: Institute of Electrical and Electronics Engineers",
	"PKI: Public Key Infrastructure ",
	"NARA: National Archives and Records Administration",
	"PMAS: Project Management Accountability System",
	"VADIR: VA Defense Information Repository",
	"OSEHRA: Open Source Electronic Health Record Alliance ",
	"RFP: Request for Proposal ",
	"QoS: Quality of Service",
	"COTS: Commercial-Off-The-Shelf",
	"PSI: Potentially Shippable Increment",
	"DICOM: Digital Imaging Communications in Medicine",
	"DSTU: Data Standard for Trial Use",
	"TDrugs: Notification of Teratogenic Drugs ",
	"EFT: ??",
	"OI&T: Office of Information & Technology",
	"IT: Information Technology",
	"SVSO: State Veteran Service Office",
	"PA&I: Performance Analysis & Integrity",
	"HCPS: Healthcare Common Procedure Coding System ",
	"REST: Representational State Transfer",
	"TAP: Transition Assistance Program",
	"MD FIRE: Medical Device Free Interoperability Requirements for the Enterprise",
	"ICD: International Classification of Diseases ",
	"CPRS: Computerized Patient Record System",
	"EP: End Product",
	"SAN: Storage Area Network",
	"SPMP: State Prescription Drug Monitoring Programs",
	"HEC: Health Executive Council",
	"JLV: Joint Legacy Viewer",
	"OPP: Office of Policy and Planning",
	"UX: User Experience",
	"NOD: Notice of Disagreement",
	"eVPR: Enterprise Virtual Patient Record ",
	"NIPRNet: Non-secure Internet Protocol  Router Network ",
	"MOU: Memorandum of Understanding",
	"OAuth2: Open Authorization 2",
	"MU: Meaningful Use",
	"VACOLS: Veterans Appeals Control and Locator Service",
	"MLLP: Minimum Lower Layer Protocol",
	"UMLS CUI: Unified Medical Language System Concept Unique Identifier ",
	"BoA: Board of Appeals",
	"SSA: Social Security Administration ",
	"POW: Prisoner of War",
	"EMS: Exam Management System",
	"iEHR: Integrated Electronic Health Records",
	"ETS: Enterprise Terminology Services ",
	"VBA: Veterans Benefits Administration",
	"STVHCS: South Texas Veterans Health Care System",
	"PRE: Pharmacy Re-engineering",
	"SNOMED: Systematized Nomenclature of Medicine",
	"ACE: Adaptive Cloud Environment",
	"VBMS-R: rating portion of VBMS",
	"LIS: Laboratory Information System",
	"ATO: Authority to Operate",
	"VDS: VistA Data Service",
	"AIDE: Agile Integrated Development Environment ",
	"PCGL: Personal Computer Guided Letters",
	"SMART: Security Management and Reporting Tool",
	"LACAS: Licensing and Certification Approval System",
	"OBPI: Office of Business Process Integration",
	"CLIM: Common Logical Information Model",
	"SMC: Special Monthly Compensation",
	"ETL: Extract Transform Load",
	"HDR: Health Data Repository",
	"MAP-D: Modern Award Processing-Development",
	"MDI: Medical Device Integration",
	"CEHRT : Certified Electronic Health Record Technology",
	"PMR: Private Medical Records",
	"Comms & PR: Communications and Public Relations",
	"SwA: Software Assurance",
	"PHIN: Public Health Information Network",
	"SLA: Service Level Agreement",
	"RMC: Records Management Center",
	"JSON: Java Script Object Notation",
	"PHIS: Pharmacy Hospital Information System ",
	"IG: Inspector General",
	"ASD: Architecture",
	"DHMSM: DoD Healthcare Management System Modernization",
	"PMO: Program Management Office",
	"WEAMS: Web Enabled Approval Management System",
	"VEIP: VistA Evolution Interoperability Plan",
	"WAN: Wide Area Network",
	"RadLex: Radiology Lexicon ",
	"DIMA: Disability ???",
	"LAN: Local Area Network",
	"HVAC: House Veterans Affairs Committee",
	"SSL/TLS: Secure Sockets Layer/Transport Security Layer",
	"CARS: Centralized Accounts Receivable System",
	"W3C: World Wide Web Consortium",
	"CPOE: Clinician Pharmacy Order Entry",
	"UDDI: Universal Description Discovery and Integration",
	"ADE: Adverse Drug Event",
	"FIPS: Federal Information Processing Standard",
	"MUMPS: Massachusetts General Hospital Utility Multi-Programming System",
	"OCLA: Office of Congressional and Legislative Affairs",
	"IDES: Integrated Disability Evaluation System",
	"AITC: Austin Information Technology Center",
	"SORN: System of Record Notice",
	"EHMP: Enterprise Health Management Platform",
	"CUI: Clinician User Interface",
	"OMB: Office of Management and Budget",
	"BIRLS: Beneficiary Identification Records Locator Subsystem",
	"SBU: Sensitive But Unclassified",
	"CDC: Centers for Disease Control",
	"STR: Service Treatment Record",
	"UCUM: Unified Code for Units of Measure ",
	"CDI: Common Data Initiative",
	"OFA&A: Office of Facilities Access and Administration",
	"OLAF: On-Line Approval File",
	"CAROLS: Centralized Accounts Receivable Online System",
	"SI: Seriously Injured",
	"OEO: Office of Economic Opportunity",
	"PIV: Personal Identity Verification ",
	"CDS: Clinical Decision Support",
	"IPC: Intake Processing Center",
	"DHCP: Decentralized Hospital Computer Program",
	"AHLTA: ",
	"LOB: Line of Business",
	"TLS: Transport Layer Security",
	"DD214: DD Form 214",
	"VistA 4: ",
	"SNOMED CT: Systematized Nomenclature of Medicine - Clinical Terms",
	"USB: Undersecretary of Benefits",
	"CVX: Codes for Vaccine Administered",
	"DPRIS: DOD Personnel Records Image Retrieval System",
	"CAS: Clinical Ancillary Services ",
	"VCIP: Veterans Claims Intake Program",
	"MST: Military Sexual Trauma",
	"DECC: Defense Enterprise Computing Centers",
	"DISA: Defense Information Systems Agency ",
	"VATAS: VA Time and Attendance System",
	"LOINC: Logical Observation Identifiers Names and Codes",
	"VLER: Virtual Lifetime Electronic Record ",
	"ARCH: Access Received Closer to Home",
	"EVSS: Electronic Veterans Self Service",
	"M-Code: Massachusetts General Hospital Utility Multi-Programming System Code",
	"QRDA: Quality Reporting Document Architecture",
	"VistA: Veterans Health Information Systems and Technology Architecture",
	"SVAC: Senate Veterans Affairs Committee",
	"HIT: Health Information Technology",
	"FISMA: Federal Information Security Management Act",
	"IIS: Immunization Information System ",
	"SDE: Service Delivery and Engineering ",
	"FAR: Federal Acquisition Regulation",
	"VHA: Veterans Health Administration",
	"C/MU: Certification/Meaningful Use",
	"ITSS: VACO campus information security people",
	"PPM: Product Platform Management",
	"GAP: Generate and Process",
	"PPS: Pharmacy Product System ",
	"OASIS: Organization for the Advancement of Structured Information Standards",
	"IV: Intravenous ",
	"HAIMS: Health Artifact and Image Management Solution",
	"comp & pen: compensation and pension",
	"NIST: National Institute of Standards and Technology",
	"VONAPP: Veterans On-Line Application",
	"VIMM: VistA Immunization Enhancements ",
	"SOA: Service Oriented Architecture",
	"VRU: Veterans Relationship Management",
	"IAF: Interoperability Alignment Framework ",
	"RAID: Redundant Array of Independent Disks ",
	"ICIB:  Interagency Clinical Informatics Board",
	"BDN: Benefits Delivery Network",
	"IRIS: Inquiry Routing and Information System",
	"GOE: Government Operating Expenses",
	"IU: Individual Unemployability",
	"SOC: Statement of Case",
	"FDCCI: Federal Data Center Consolidation Initiative",
	"OFO: Office of Field Operations",
	"IBPE: Internal Business Partner Extranet ",
	"ESB: Enterprise Service Bus",
	"HTTPS: Hypertext Transport Protocol Secure",
	"DoS: Denial-of-Service ",
	"VISN: Veterans Integrated Service Network",
	"ICR: Intelligent Character Recognition",
	"ESM: Enterprise System Manager",
	"MRS: Military Record Specialist",
	"VAMC: Veterans Affairs Medical Center",
	"nexus statement: evidence of service connection",
	"ICU: Intensive Care Unit",
	"HPD: Health Provider Directory ",
	"HHS: Health and Human Services",
	"VSR: Veterans Service Representative",
	"SDO: Standards Development Organizations",
	"SAML: Security Assertion Markup Language",
	"DoD: Department of Defense",
	"UAT: User Acceptance Testing",
	"VSA: VistA Service Assembly",
	"CATS: Clinical Advisory Technical Services",
	"SNOD: Standardized Notice of Disagreement",
	"ONC: Office of the National Coordinator for Health Information Technology ",
	"Vx: VistA Exchange ",
	"NCA: National Cemetery Administration",
	"SDN: Software Defined Network",
	"GFE: Government Furnished Equipment ",
	"HIPAA: Health Insurance Portability and Accountability Act",
	"SOAP: Simple Object Access Protocol",
	"OGC: Office of General Counsel",
	"VSO: Veterans Service Organization"
]